/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.srmo.tgms.logger;

import com.dslplatform.json.DslJson;
import com.dslplatform.json.runtime.Settings;
import com.github.srmo.tgms.logger.ui.MainFrame;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.reflect.InvocationTargetException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    private final DslJson.Settings settings = Settings.withRuntime().includeServiceLoader();
    private final DslJson<Object> json = new DslJson<Object>(settings);
    private static MainFrame mainFrame;

    private static final Logger LOG = LoggerFactory.getLogger("Tgms-Logger");
    public static void main(String[] args) throws InvocationTargetException, InterruptedException {

        LOG.info("Starting application...");
        // try and find the user properties


//                new MainFrame("Hello World");
//
//        Schedule a job for the event dispatch thread:
//        creating and showing this application's GUI.
        javax.swing.SwingUtilities.invokeAndWait(new Runnable() {
            public void run() {
                mainFrame = new MainFrame("Hello World");
            }
        });

        new AppController(mainFrame).doIt();
    }

}
